# Generated by Django 3.2.13 on 2023-03-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_maincategory_cate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subcategory'),
        ),
    ]
