# Generated by Django 3.2.13 on 2023-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_alter_childcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
