# Generated by Django 3.2.13 on 2023-03-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0034_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
